[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"

[dependencies]
trie-root = "0.15.2"
codec = { package = "parity-scale-codec", version = "1.0.0" }
sp-io = { path = "../../../primitives/io" }
state-machine = { package = "sp-state-machine", path = "../../../primitives/state-machine" }
sc-executor = { path = "../../../client/executor" }
primitives = { package = "sp-core", path = "../../../primitives/core" }
trie = { package = "sp-trie", path = "../../../primitives/trie" }
node-primitives = { path = "../primitives" }
node-runtime = { path = "../runtime" }

[dev-dependencies]
app-crypto = { package = "sc-application-crypto", path = "../../../primitives/application-crypto" }
balances = { package = "pallet-balances", path = "../../../frame/balances" }
contracts = { package = "pallet-contracts", path = "../../../frame/contracts" }
criterion = "0.3.0"
grandpa = { package = "pallet-grandpa", path = "../../../frame/grandpa" }
imonline = { package = "pallet-im-online", path = "../../../frame/im-online" }
indices = { package = "pallet-indices", path = "../../../frame/indices" }
node-testing = { path = "../testing" }
runtime_support = { package = "frame-support", path = "../../../frame/support" }
session = { package = "pallet-session", path = "../../../frame/session" }
sp-runtime = { path = "../../../primitives/runtime" }
system = { package = "frame-system", path = "../../../frame/system" }
test-client = { package = "substrate-test-client", path = "../../../test/utils/client" }
timestamp = { package = "pallet-timestamp", path = "../../../frame/timestamp" }
transaction-payment = { package = "pallet-transaction-payment", path = "../../../frame/transaction-payment" }
treasury = { package = "pallet-treasury", path = "../../../frame/treasury" }
wabt = "0.9.2"

[features]
wasmtime = [
    "sc-executor/wasmtime",
]
wasmi-errno = [
	"sc-executor/wasmi-errno",
]
stress-test = []

[[bench]]
name = "bench"
harness = false
