[package]
name = "srml-bridge"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false }
client = { package = "substrate-client", path = "../../core/client" }
fg = { package = "substrate-finality-grandpa", path = "../../core/finality-grandpa/" }
fg_primitives = { package = "substrate-finality-grandpa-primitives", path ="../../core/finality-grandpa/primitives", default-features = false }
grandpa = { package = "finality-grandpa", version = "0.9.1", default-features = false, features = ["derive-codec"] }
hash-db = { version = "0.15.2", default-features = false }
primitives = { package = "substrate-primitives",  path = "../../core/primitives", default-features = false }
num = { package = "num-traits", version = "0.2", default-features = false }
rstd = { package = "sr-std", path = "../../core/sr-std", default-features = false }
runtime-io = { package = "sr-io", path = "../../core/sr-io", default-features = false }
session = { package = "srml-session", path = "../session", default-features = false, features = ["historical"] }
serde = { version = "1.0", optional = true }
sr-primitives = { path = "../../core/sr-primitives", default-features = false }
support = { package = "srml-support", path = "../support", default-features = false }
system = { package = "srml-system", path = "../system", default-features = false }
trie = { package = "substrate-trie", path = "../../core/trie", default-features = false }

[dev-dependencies]
keyring = { package = "substrate-keyring", path = "../../core/keyring" }
state-machine = { package = "substrate-state-machine",  path = "../../core/state-machine" }
test-client = { package = "substrate-test-runtime-client", path = "../../core/test-runtime/client" }

[features]
default = ["std"]
std = [
	"serde",
	"codec/std",
	"session/std",
	"sr-primitives/std",
	"support/std",
	"system/std",
	"trie/std",
	"runtime-io/std",
]
